import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'bn' | 'te';

export const translations = {
  en: {
    // Onboarding
    appTitle: 'AI-Powered Health Checker',
    appSubtitle: 'Check your symptoms anytime, anywhere – even offline',
    feature1: 'Works offline on your device',
    feature2: 'Your data stays private',
    feature3: 'Available in multiple languages',
    languageLabel: 'Select Language / भाषा चुनें',
    getStarted: 'Get Started',
    
    // Home
    welcomeBack: 'Welcome back!',
    howFeeling: 'How are you feeling today?',
    checkSymptoms: 'Check Symptoms',
    history: 'History',
    previousChecks: 'Previous checks',
    settings: 'Settings',
    preferences: 'Preferences',
    quickStats: 'Quick Stats',
    totalChecks: 'Total checks',
    lastCheck: 'Last check',
    daysAgo: 'days ago',
    signIn: 'Sign In',
    signedIn: 'Signed In',
    dataPrivacyNotice: 'All your health data stays securely on your device',
    healthAssistant: 'AI-Powered Health Assistant',
    
    // Symptom Input
    symptomCheck: 'Symptom Check',
    selectSymptoms: 'Select your symptoms',
    howAreYouFeeling: 'How are you feeling?',
    selectFromCommon: 'Select from common symptoms or add your own',
    typeSymptom: 'Type a symptom...',
    commonSymptoms: 'Common Symptoms',
    yourSymptoms: 'Your Symptoms',
    feverTemperature: 'Fever Temperature (optional)',
    celsius: 'Celsius (°C)',
    fahrenheit: 'Fahrenheit (°F)',
    highFever: 'High fever - seek medical attention',
    mildFever: 'Mild fever',
    normalTemperature: 'Normal temperature',
    analyzeSymptoms: 'Analyze Symptoms',
    
    // Symptom names
    headache: 'Headache',
    fever: 'Fever',
    cough: 'Cough',
    fatigue: 'Fatigue',
    nausea: 'Nausea',
    dizziness: 'Dizziness',
    chestPain: 'Chest Pain',
    shortnessOfBreath: 'Shortness of Breath',
    stomachPain: 'Stomach Pain',
    soreThroat: 'Sore Throat',
    bodyAches: 'Body Aches',
    lossOfAppetite: 'Loss of Appetite',
    
    // Results
    results: 'Results',
    urgent: 'Urgent - Seek immediate care',
    consultSoon: 'Consult Soon - Schedule appointment',
    safeToMonitor: 'Safe to Monitor - Keep an eye on symptoms',
    analysisSummary: 'Analysis Summary',
    conditionsAnalyzed: 'Conditions analyzed',
    possibleConditions: 'Possible Conditions',
    match: 'match',
    symptomsAnalyzed: 'Symptoms Analyzed',
    viewCareAdvice: 'View Care Advice',
    bookAppointment: 'Book Appointment',
    medicalDisclaimer: 'Medical Disclaimer: This AI assessment is for informational purposes only. Always consult healthcare professionals for medical concerns. If experiencing severe symptoms, seek immediate medical attention.',
    
    // Advice
    careAdvice: 'Care Advice',
    immediateActionRequired: 'Immediate Action Required',
    scheduleMedicalConsultation: 'Schedule Medical Consultation',
    selfCareMonitoring: 'Self-Care & Monitoring',
    recommendedNextSteps: 'Recommended Next Steps',
    homeCareTips: 'Home Care Tips',
    whenToSeekCare: 'When to Seek Immediate Care',
    urgentCare: 'Urgent Care',
    callHealthHotline: 'Call Health Hotline',
    emergency: 'Emergency',
    callImmediately: 'Call immediately if you experience life-threatening symptoms',
    
    // Advice texts
    seekEmergency: 'Seek emergency medical care immediately',
    callEmergencyServices: 'Call emergency services if symptoms worsen',
    doNotWait: 'Do not wait - go to the nearest hospital',
    haveSomeoneDrive: 'Have someone drive you or call an ambulance',
    contactProvider: 'Contact your healthcare provider within 24-48 hours',
    monitorClosely: 'Monitor symptoms closely',
    avoidStrenuous: 'Avoid strenuous activities',
    keepDiary: 'Keep a symptom diary',
    getPlentyRest: 'Get plenty of rest',
    stayHydrated: 'Stay hydrated with clear fluids',
    maintainComfortable: 'Maintain a comfortable room temperature',
    takeOTC: 'Take over-the-counter pain relief if needed',
    monitorForChanges: 'Monitor symptoms for any changes',
    restAndRecover: 'Rest and allow your body to recover',
    contactDoctor: 'Contact a doctor if symptoms worsen',
    keepTrack: 'Keep track of how you feel',
    getSleep: 'Get 7-9 hours of sleep',
    drinkWater: 'Drink plenty of water',
    eatLight: 'Eat light, nutritious meals',
    useHumidifier: 'Use a humidifier if needed',
    takeWarmBaths: 'Take warm baths or showers',
    symptomsWorsen: 'Symptoms suddenly worsen or become severe',
    difficultyBreathing: 'Difficulty breathing or chest pain',
    highFeverWarning: 'High fever (over 103°F/39.4°C)',
    severeHeadache: 'Severe headache or confusion',
    persistentVomiting: 'Persistent vomiting or signs of dehydration',
    
    // History
    noHistoryYet: 'No history yet',
    checksWillAppear: 'Your symptom checks will appear here',
    symptoms: 'Symptoms',
    assessment: 'Assessment',
    
    // Settings
    profileInformation: 'Profile Information',
    fullName: 'Full Name',
    enterName: 'Enter your name',
    age: 'Age',
    enterAge: 'Enter your age',
    gender: 'Gender',
    selectGender: 'Select gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    preferNotToSay: 'Prefer not to say',
    privacyData: 'Privacy & Data',
    allDataOnDevice: 'All data stays on device',
    healthInfoPrivate: 'Your health information is processed locally and never sent to external servers.',
    saveSymptomHistory: 'Save symptom history',
    keepRecord: 'Keep a record of your checks',
    analyticsAnonymous: 'Analytics (Anonymous)',
    helpImprove: 'Help improve the app',
    appPreferences: 'App Preferences',
    language: 'Language / भाषा',
    darkMode: 'Dark mode',
    useDarkTheme: 'Use dark theme',
    notifications: 'Notifications',
    healthReminders: 'Health reminders',
    getReminded: 'Get reminded to check symptoms',
    appointmentReminders: 'Appointment reminders',
    remindersForBooked: 'Reminders for booked appointments',
    dataManagement: 'Data Management',
    clearAllHistory: 'Clear all history',
    appVersion: 'AI-Powered Health Checker v1.0.0',
    copyright: '© 2024 - Made with care for your health',
    
    // Appointment Booking
    backToResults: 'Back to Results',
    findNearbyClinics: 'Find Nearby Clinics',
    selectClinic: 'Select a clinic to book your appointment',
    nextAvailable: 'Next available',
    select: 'Select',
    bookingAt: 'Booking at',
    patientInformation: 'Patient Information',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    reasonForVisit: 'Reason for Visit',
    briefDescription: 'Brief description of your symptoms',
    chooseDifferentClinic: 'Choose Different Clinic',
    confirmAppointment: 'Confirm Appointment',
    
    // Loading
    analyzingSymptoms: 'Analyzing Your Symptoms',
    aiProcessing: 'Our AI is processing your information...',
  },
  hi: {
    // Onboarding
    appTitle: 'एआई-संचालित स्वास्थ्य जांचकर्ता',
    appSubtitle: 'अपने लक्षणों की जांच कभी भी, कहीं भी करें – ऑफ़लाइन भी',
    feature1: 'आपके डिवाइस पर ऑफ़लाइन काम करता है',
    feature2: 'आपका डेटा निजी रहता है',
    feature3: 'कई भाषाओं में उपलब्ध',
    languageLabel: 'भाषा चुनें / Select Language',
    getStarted: 'शुरू करें',
    
    // Home
    welcomeBack: 'वापसी पर स्वागत है!',
    howFeeling: 'आज आप कैसा महसूस कर रहे हैं?',
    checkSymptoms: 'लक्षण जांचें',
    history: 'इतिहास',
    previousChecks: 'पिछली जांच',
    settings: 'सेटिंग्स',
    preferences: 'प्राथमिकताएं',
    quickStats: 'त्वरित आंकड़े',
    totalChecks: 'कुल जांच',
    lastCheck: 'अंतिम जांच',
    daysAgo: 'दिन पहले',
    signIn: 'साइन इन करें',
    signedIn: 'साइन इन',
    dataPrivacyNotice: 'आपका सभी स्वास्थ्य डेटा आपके डिवाइस पर सुरक्षित रहता है',
    healthAssistant: 'एआई-संचालित स्वास्थ्य सहायक',
    
    // Symptom Input
    symptomCheck: 'लक्षण जांच',
    selectSymptoms: 'अपने लक्षण चुनें',
    howAreYouFeeling: 'आप कैसा महसूस कर रहे हैं?',
    selectFromCommon: 'सामान्य लक्षणों में से चुनें या अपना जोड़ें',
    typeSymptom: 'लक्षण टाइप करें...',
    commonSymptoms: 'सामान्य लक्षण',
    yourSymptoms: 'आपके लक्षण',
    feverTemperature: 'बुखार का तापमान (वैकल्पिक)',
    celsius: 'सेल्सियस (°C)',
    fahrenheit: 'फारेनहाइट (°F)',
    highFever: 'तेज बुखार - चिकित्सा सहायता लें',
    mildFever: 'हल्का बुखार',
    normalTemperature: 'सामान्य तापमान',
    analyzeSymptoms: 'लक्षण विश्लेषण करें',
    
    // Symptom names
    headache: 'सिर दर्द',
    fever: 'बुखार',
    cough: 'खांसी',
    fatigue: 'थकान',
    nausea: 'मतली',
    dizziness: 'चक्कर आना',
    chestPain: 'सीने में दर्द',
    shortnessOfBreath: 'सांस की तकलीफ',
    stomachPain: 'पेट दर्द',
    soreThroat: 'गले में खराश',
    bodyAches: 'शरीर में दर्द',
    lossOfAppetite: 'भूख न लगना',
    
    // Results
    results: 'परिणाम',
    urgent: 'आपातकालीन - तुरंत देखभाल लें',
    consultSoon: 'जल्द परामर्श लें - अपॉइंटमेंट शेड्यूल करें',
    safeToMonitor: 'निगरानी में रखें - लक्षणों पर नजर रखें',
    analysisSummary: 'विश्लेषण सारांश',
    conditionsAnalyzed: 'विश्लेषित स्थितियां',
    possibleConditions: 'संभावित स्थितियां',
    match: 'मिलान',
    symptomsAnalyzed: 'विश्लेषित लक्षण',
    viewCareAdvice: 'देखभाल सलाह देखें',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    medicalDisclaimer: 'चिकित्सा अस्वीकरण: यह एआई मूल्यांकन केवल सूचनात्मक उद्देश्यों के लिए है। चिकित्सा संबंधी चिंताओं के लिए हमेशा स्वास्थ्य पेशेवरों से परामर्श करें।',
    
    // Advice
    careAdvice: 'देखभाल सलाह',
    immediateActionRequired: 'तुरंत कार्रवाई आवश्यक',
    scheduleMedicalConsultation: 'चिकित्सा परामर्श शेड्यूल करें',
    selfCareMonitoring: 'स्व-देखभाल और निगरानी',
    recommendedNextSteps: 'अनुशंसित अगले कदम',
    homeCareTips: 'घरेलू देखभाल सुझाव',
    whenToSeekCare: 'तुरंत देखभाल कब लें',
    urgentCare: 'आपातकालीन देखभाल',
    callHealthHotline: 'स्वास्थ्य हॉटलाइन कॉल करें',
    emergency: 'आपातकालीन',
    callImmediately: 'जानलेवा लक्षण होने पर तुरंत कॉल करें',
    
    // Advice texts
    seekEmergency: 'तुरंत आपातकालीन चिकित्सा देखभाल लें',
    callEmergencyServices: 'लक्षण बिगड़ने पर आपातकालीन सेवाओं को कॉल करें',
    doNotWait: 'प्रतीक्षा न करें - निकटतम अस्पताल जाएं',
    haveSomeoneDrive: 'किसी से आपको ले जाने के लिए कहें या एम्बुलेंस बुलाएं',
    contactProvider: '24-48 घंटों के भीतर अपने स्वास्थ्य सेवा प्रदाता से संपर्क करें',
    monitorClosely: 'लक्षणों की बारीकी से निगरानी करें',
    avoidStrenuous: 'कठिन गतिविधियों से बचें',
    keepDiary: 'लक्षण डायरी रखें',
    getPlentyRest: 'पर्याप्त आराम करें',
    stayHydrated: 'साफ तरल पदार्थों से हाइड्रेटेड रहें',
    maintainComfortable: 'आरामदायक कमरे का तापमान बनाए रखें',
    takeOTC: 'जरूरत पड़ने पर ओवर-द-काउंटर दर्द निवारक लें',
    monitorForChanges: 'किसी भी बदलाव के लिए लक्षणों की निगरानी करें',
    restAndRecover: 'आराम करें और अपने शरीर को ठीक होने दें',
    contactDoctor: 'लक्षण बिगड़ने पर डॉक्टर से संपर्क करें',
    keepTrack: 'अपनी स्थिति पर नज़र रखें',
    getSleep: '7-9 घंटे की नींद लें',
    drinkWater: 'खूब पानी पिएं',
    eatLight: 'हल्का, पौष्टिक भोजन करें',
    useHumidifier: 'जरूरत पड़ने पर ह्यूमिडिफायर का उपयोग करें',
    takeWarmBaths: 'गर्म स्नान करें',
    symptomsWorsen: 'लक्षण अचानक बिगड़ें या गंभीर हों',
    difficultyBreathing: 'सांस लेने में कठिनाई या सीने में दर्द',
    highFeverWarning: 'तेज बुखार (103°F/39.4°C से अधिक)',
    severeHeadache: 'तीव्र सिरदर्द या भ्रम',
    persistentVomiting: 'लगातार उल्टी या निर्जलीकरण के संकेत',
    
    // History
    noHistoryYet: 'अभी तक कोई इतिहास नहीं',
    checksWillAppear: 'आपकी लक्षण जांच यहां दिखाई देगी',
    symptoms: 'लक्षण',
    assessment: 'मूल्यांकन',
    
    // Settings
    profileInformation: 'प्रोफ़ाइल जानकारी',
    fullName: 'पूरा नाम',
    enterName: 'अपना नाम दर्ज करें',
    age: 'आयु',
    enterAge: 'अपनी आयु दर्ज करें',
    gender: 'लिंग',
    selectGender: 'लिंग चुनें',
    male: 'पुरुष',
    female: 'महिला',
    other: 'अन्य',
    preferNotToSay: 'बताना नहीं चाहते',
    privacyData: 'गोपनीयता और डेटा',
    allDataOnDevice: 'सभी डेटा डिवाइस पर रहता है',
    healthInfoPrivate: 'आपकी स्वास्थ्य जानकारी स्थानीय रूप से प्रोसेस होती है और कभी बाहरी सर्वर पर नहीं भेजी जाती।',
    saveSymptomHistory: 'लक्षण इतिहास सहेजें',
    keepRecord: 'अपनी जांच का रिकॉर्ड रखें',
    analyticsAnonymous: 'एनालिटिक्स (गुमनाम)',
    helpImprove: 'ऐप को बेहतर बनाने में मदद करें',
    appPreferences: 'ऐप प्राथमिकताएं',
    language: 'भाषा / Language',
    darkMode: 'डार्क मोड',
    useDarkTheme: 'डार्क थीम का उपयोग करें',
    notifications: 'सूचनाएं',
    healthReminders: 'स्वास्थ्य रिमाइंडर',
    getReminded: 'लक्षण जांचने की याद दिलाएं',
    appointmentReminders: 'अपॉइंटमेंट रिमाइंडर',
    remindersForBooked: 'बुक किए गए अपॉइंटमेंट के लिए रिमाइंडर',
    dataManagement: 'डेटा प्रबंधन',
    clearAllHistory: 'सारा इतिहास साफ करें',
    appVersion: 'एआई-संचालित स्वास्थ्य जांचकर्ता v1.0.0',
    copyright: '© 2024 - आपके स्वास्थ्य के लिए बनाया गया',
    
    // Appointment Booking
    backToResults: 'परिणामों पर वापस',
    findNearbyClinics: 'पास के क्लिनिक खोजें',
    selectClinic: 'अपॉइंटमेंट बुक करने के लिए क्लिनिक चुनें',
    nextAvailable: 'अगला उपलब्ध',
    select: 'चुनें',
    bookingAt: 'बुकिंग',
    patientInformation: 'मरीज की जानकारी',
    phoneNumber: 'फोन नंबर',
    emailAddress: 'ईमेल पता',
    reasonForVisit: 'विजिट का कारण',
    briefDescription: 'अपने लक्षणों का संक्षिप्त विवरण',
    chooseDifferentClinic: 'अलग क्लिनिक चुनें',
    confirmAppointment: 'अपॉइंटमेंट की पुष्टि करें',
    
    // Loading
    analyzingSymptoms: 'आपके लक्षणों का विश्लेषण हो रहा है',
    aiProcessing: 'हमारा एआई आपकी जानकारी प्रोसेस कर रहा है...',
  },
  bn: {
    // Onboarding
    appTitle: 'এআই-চালিত স্বাস্থ্য পরীক্ষক',
    appSubtitle: 'যেকোনো সময়, যেকোনো জায়গায় আপনার লক্ষণ পরীক্ষা করুন – অফলাইনেও',
    feature1: 'আপনার ডিভাইসে অফলাইনে কাজ করে',
    feature2: 'আপনার ডেটা ব্যক্তিগত থাকে',
    feature3: 'একাধিক ভাষায় উপলব্ধ',
    languageLabel: 'ভাষা নির্বাচন করুন / Select Language',
    getStarted: 'শুরু করুন',
    
    // Home
    welcomeBack: 'স্বাগতম!',
    howFeeling: 'আজ আপনি কেমন অনুভব করছেন?',
    checkSymptoms: 'লক্ষণ পরীক্ষা',
    history: 'ইতিহাস',
    previousChecks: 'আগের পরীক্ষা',
    settings: 'সেটিংস',
    preferences: 'পছন্দ',
    quickStats: 'দ্রুত পরিসংখ্যান',
    totalChecks: 'মোট পরীক্ষা',
    lastCheck: 'শেষ পরীক্ষা',
    daysAgo: 'দিন আগে',
    signIn: 'সাইন ইন',
    signedIn: 'সাইন ইন করা',
    dataPrivacyNotice: 'আপনার সমস্ত স্বাস্থ্য ডেটা আপনার ডিভাইসে সুরক্ষিত থাকে',
    healthAssistant: 'এআই-চালিত স্বাস্থ্য সহকারী',
    
    // Symptom Input
    symptomCheck: 'লক্ষণ পরীক্ষা',
    selectSymptoms: 'আপনার লক্ষণ নির্বাচন করুন',
    howAreYouFeeling: 'আপনি কেমন অনুভব করছেন?',
    selectFromCommon: 'সাধারণ লক্ষণ থেকে নির্বাচন করুন বা নিজের যোগ করুন',
    typeSymptom: 'লক্ষণ টাইপ করুন...',
    commonSymptoms: 'সাধারণ লক্ষণ',
    yourSymptoms: 'আপনার লক্ষণ',
    feverTemperature: 'জ্বরের তাপমাত্রা (ঐচ্ছিক)',
    celsius: 'সেলসিয়াস (°C)',
    fahrenheit: 'ফারেনহাইট (°F)',
    highFever: 'উচ্চ জ্বর - চিকিৎসা সহায়তা নিন',
    mildFever: 'হালকা জ্বর',
    normalTemperature: 'স্বাভাবিক তাপমাত্রা',
    analyzeSymptoms: 'লক্ষণ বিশ্লেষণ',
    
    // Symptom names
    headache: 'মাথাব্যথা',
    fever: 'জ্বর',
    cough: 'কাশি',
    fatigue: 'ক্লান্তি',
    nausea: 'বমি বমি ভাব',
    dizziness: 'মাথা ঘোরা',
    chestPain: 'বুকে ব্যথা',
    shortnessOfBreath: 'শ্বাসকষ্ট',
    stomachPain: 'পেটে ব্যথা',
    soreThroat: 'গলা ব্যথা',
    bodyAches: 'শরীরে ব্যথা',
    lossOfAppetite: 'ক্ষুধা কমে যাওয়া',
    
    // Results
    results: 'ফলাফল',
    urgent: 'জরুরি - অবিলম্বে যত্ন নিন',
    consultSoon: 'শীঘ্রই পরামর্শ নিন - অ্যাপয়েন্টমেন্ট নিন',
    safeToMonitor: 'পর্যবেক্ষণে রাখুন - লক্ষণগুলিতে নজর রাখুন',
    analysisSummary: 'বিশ্লেষণ সারাংশ',
    conditionsAnalyzed: 'বিশ্লেষিত অবস্থা',
    possibleConditions: 'সম্ভাব্য অবস্থা',
    match: 'মিল',
    symptomsAnalyzed: 'বিশ্লেষিত লক্ষণ',
    viewCareAdvice: 'যত্ন পরামর্শ দেখুন',
    bookAppointment: 'অ্যাপয়েন্টমেন্ট বুক করুন',
    medicalDisclaimer: 'চিকিৎসা দাবিত্যাগ: এই এআই মূল্যায়ন শুধুমাত্র তথ্যমূলক উদ্দেশ্যে। চিকিৎসা সংক্রান্ত উদ্বেগের জন্য সর্বদা স্বাস্থ্য পেশাদারদের সাথে পরামর্শ করুন।',
    
    // Advice
    careAdvice: 'যত্ন পরামর্শ',
    immediateActionRequired: 'অবিলম্বে পদক্ষেপ প্রয়োজন',
    scheduleMedicalConsultation: 'চিকিৎসা পরামর্শ নির্ধারণ করুন',
    selfCareMonitoring: 'স্ব-যত্ন ও পর্যবেক্ষণ',
    recommendedNextSteps: 'প্রস্তাবিত পরবর্তী পদক্ষেপ',
    homeCareTips: 'ঘরোয়া যত্ন টিপস',
    whenToSeekCare: 'কখন অবিলম্বে যত্ন নেবেন',
    urgentCare: 'জরুরি যত্ন',
    callHealthHotline: 'স্বাস্থ্য হটলাইনে কল করুন',
    emergency: 'জরুরি',
    callImmediately: 'জীবন-হুমকিপূর্ণ লক্ষণ হলে অবিলম্বে কল করুন',
    
    // Advice texts
    seekEmergency: 'অবিলম্বে জরুরি চিকিৎসা সেবা নিন',
    callEmergencyServices: 'লক্ষণ খারাপ হলে জরুরি সেবায় কল করুন',
    doNotWait: 'অপেক্ষা করবেন না - নিকটতম হাসপাতালে যান',
    haveSomeoneDrive: 'কাউকে নিয়ে যেতে বলুন বা অ্যাম্বুলেন্স ডাকুন',
    contactProvider: '24-48 ঘন্টার মধ্যে আপনার স্বাস্থ্যসেবা প্রদানকারীর সাথে যোগাযোগ করুন',
    monitorClosely: 'লক্ষণগুলি ঘনিষ্ঠভাবে পর্যবেক্ষণ করুন',
    avoidStrenuous: 'কঠোর কার্যকলাপ এড়িয়ে চলুন',
    keepDiary: 'লক্ষণ ডায়েরি রাখুন',
    getPlentyRest: 'প্রচুর বিশ্রাম নিন',
    stayHydrated: 'পরিষ্কার তরল দিয়ে হাইড্রেটেড থাকুন',
    maintainComfortable: 'আরামদায়ক ঘরের তাপমাত্রা বজায় রাখুন',
    takeOTC: 'প্রয়োজনে ওভার-দ্য-কাউন্টার ব্যথানাশক নিন',
    monitorForChanges: 'যেকোনো পরিবর্তনের জন্য লক্ষণ পর্যবেক্ষণ করুন',
    restAndRecover: 'বিশ্রাম নিন এবং আপনার শরীরকে সুস্থ হতে দিন',
    contactDoctor: 'লক্ষণ খারাপ হলে ডাক্তারের সাথে যোগাযোগ করুন',
    keepTrack: 'আপনি কেমন অনুভব করছেন তার ট্র্যাক রাখুন',
    getSleep: '7-9 ঘন্টা ঘুমান',
    drinkWater: 'প্রচুর পানি পান করুন',
    eatLight: 'হালকা, পুষ্টিকর খাবার খান',
    useHumidifier: 'প্রয়োজনে হিউমিডিফায়ার ব্যবহার করুন',
    takeWarmBaths: 'গরম স্নান করুন',
    symptomsWorsen: 'লক্ষণ হঠাৎ খারাপ বা গুরুতর হয়',
    difficultyBreathing: 'শ্বাস নিতে অসুবিধা বা বুকে ব্যথা',
    highFeverWarning: 'উচ্চ জ্বর (103°F/39.4°C এর উপরে)',
    severeHeadache: 'তীব্র মাথাব্যথা বা বিভ্রান্তি',
    persistentVomiting: 'ক্রমাগত বমি বা পানিশূন্যতার লক্ষণ',
    
    // History
    noHistoryYet: 'এখনও কোনো ইতিহাস নেই',
    checksWillAppear: 'আপনার লক্ষণ পরীক্ষা এখানে দেখাবে',
    symptoms: 'লক্ষণ',
    assessment: 'মূল্যায়ন',
    
    // Settings
    profileInformation: 'প্রোফাইল তথ্য',
    fullName: 'পুরো নাম',
    enterName: 'আপনার নাম লিখুন',
    age: 'বয়স',
    enterAge: 'আপনার বয়স লিখুন',
    gender: 'লিঙ্গ',
    selectGender: 'লিঙ্গ নির্বাচন করুন',
    male: 'পুরুষ',
    female: 'মহিলা',
    other: 'অন্যান্য',
    preferNotToSay: 'বলতে চাই না',
    privacyData: 'গোপনীয়তা ও ডেটা',
    allDataOnDevice: 'সমস্ত ডেটা ডিভাইসে থাকে',
    healthInfoPrivate: 'আপনার স্বাস্থ্য তথ্য স্থানীয়ভাবে প্রক্রিয়া করা হয় এবং কখনও বাহ্যিক সার্ভারে পাঠানো হয় না।',
    saveSymptomHistory: 'লক্ষণ ইতিহাস সংরক্ষণ',
    keepRecord: 'আপনার পরীক্ষার রেকর্ড রাখুন',
    analyticsAnonymous: 'অ্যানালিটিক্স (বেনামী)',
    helpImprove: 'অ্যাপ উন্নত করতে সাহায্য করুন',
    appPreferences: 'অ্যাপ পছন্দ',
    language: 'ভাষা / Language',
    darkMode: 'ডার্ক মোড',
    useDarkTheme: 'ডার্ক থিম ব্যবহার করুন',
    notifications: 'বিজ্ঞপ্তি',
    healthReminders: 'স্বাস্থ্য অনুস্মারক',
    getReminded: 'লক্ষণ পরীক্ষা করতে মনে করিয়ে দিন',
    appointmentReminders: 'অ্যাপয়েন্টমেন্ট অনুস্মারক',
    remindersForBooked: 'বুক করা অ্যাপয়েন্টমেন্টের জন্য অনুস্মারক',
    dataManagement: 'ডেটা ব্যবস্থাপনা',
    clearAllHistory: 'সমস্ত ইতিহাস মুছুন',
    appVersion: 'এআই-চালিত স্বাস্থ্য পরীক্ষক v1.0.0',
    copyright: '© 2024 - আপনার স্বাস্থ্যের জন্য তৈরি',
    
    // Appointment Booking
    backToResults: 'ফলাফলে ফিরে যান',
    findNearbyClinics: 'কাছের ক্লিনিক খুঁজুন',
    selectClinic: 'অ্যাপয়েন্টমেন্ট বুক করতে ক্লিনিক নির্বাচন করুন',
    nextAvailable: 'পরবর্তী উপলব্ধ',
    select: 'নির্বাচন',
    bookingAt: 'বুকিং',
    patientInformation: 'রোগীর তথ্য',
    phoneNumber: 'ফোন নম্বর',
    emailAddress: 'ইমেইল ঠিকানা',
    reasonForVisit: 'ভিজিটের কারণ',
    briefDescription: 'আপনার লক্ষণের সংক্ষিপ্ত বিবরণ',
    chooseDifferentClinic: 'ভিন্ন ক্লিনিক বেছে নিন',
    confirmAppointment: 'অ্যাপয়েন্টমেন্ট নিশ্চিত করুন',
    
    // Loading
    analyzingSymptoms: 'আপনার লক্ষণ বিশ্লেষণ হচ্ছে',
    aiProcessing: 'আমাদের এআই আপনার তথ্য প্রক্রিয়া করছে...',
  },
  te: {
    // Onboarding
    appTitle: 'AI-శక్తితో పనిచేసే ఆరోగ్య పరీక్ష',
    appSubtitle: 'ఎప్పుడైనా, ఎక్కడైనా మీ లక్షణాలను తనిఖీ చేయండి – ఆఫ్‌లైన్‌లో కూడా',
    feature1: 'మీ పరికరంలో ఆఫ్‌లైన్‌లో పనిచేస్తుంది',
    feature2: 'మీ డేటా ప్రైవేట్‌గా ఉంటుంది',
    feature3: 'అనేక భాషలలో అందుబాటులో ఉంది',
    languageLabel: 'భాష ఎంచుకోండి / Select Language',
    getStarted: 'ప్రారంభించండి',
    
    // Home
    welcomeBack: 'తిరిగి స్వాగతం!',
    howFeeling: 'మీరు ఈ రోజు ఎలా అనుభవిస్తున్నారు?',
    checkSymptoms: 'లక్షణాలు తనిఖీ చేయండి',
    history: 'చరిత్ర',
    previousChecks: 'మునుపటి తనిఖీలు',
    settings: 'సెట్టింగ్‌లు',
    preferences: 'ప్రాధాన్యతలు',
    quickStats: 'త్వరిత గణాంకాలు',
    totalChecks: 'మొత్తం తనిఖీలు',
    lastCheck: 'చివరి తనిఖీ',
    daysAgo: 'రోజుల క్రితం',
    signIn: 'సైన్ ఇన్',
    signedIn: 'సైన్ ఇన్ అయ్యారు',
    dataPrivacyNotice: 'మీ మొత్తం ఆరోగ్య డేటా మీ పరికరంలో సురక్షితంగా ఉంటుంది',
    healthAssistant: 'AI-శక్తితో ఆరోగ్య సహాయకుడు',
    
    // Symptom Input
    symptomCheck: 'లక్షణ తనిఖీ',
    selectSymptoms: 'మీ లక్షణాలను ఎంచుకోండి',
    howAreYouFeeling: 'మీరు ఎలా అనుభవిస్తున్నారు?',
    selectFromCommon: 'సాధారణ లక్షణాల నుండి ఎంచుకోండి లేదా మీదే జోడించండి',
    typeSymptom: 'లక్షణాన్ని టైప్ చేయండి...',
    commonSymptoms: 'సాధారణ లక్షణాలు',
    yourSymptoms: 'మీ లక్షణాలు',
    feverTemperature: 'జ్వరం ఉష్ణోగ్రత (ఐచ్ఛికం)',
    celsius: 'సెల్సియస్ (°C)',
    fahrenheit: 'ఫారెన్‌హీట్ (°F)',
    highFever: 'తీవ్ర జ్వరం - వైద్య సహాయం తీసుకోండి',
    mildFever: 'తేలికపాటి జ్వరం',
    normalTemperature: 'సాధారణ ఉష్ణోగ్రత',
    analyzeSymptoms: 'లక్షణాలను విశ్లేషించండి',
    
    // Symptom names
    headache: 'తలనొప్పి',
    fever: 'జ్వరం',
    cough: 'దగ్గు',
    fatigue: 'అలసట',
    nausea: 'వికారం',
    dizziness: 'తల తిరగడం',
    chestPain: 'ఛాతీ నొప్పి',
    shortnessOfBreath: 'శ్వాస ఆడకపోవడం',
    stomachPain: 'కడుపు నొప్పి',
    soreThroat: 'గొంతు నొప్పి',
    bodyAches: 'శరీరం నొప్పులు',
    lossOfAppetite: 'ఆకలి లేకపోవడం',
    
    // Results
    results: 'ఫలితాలు',
    urgent: 'అత్యవసరం - వెంటనే సంరక్షణ తీసుకోండి',
    consultSoon: 'త్వరలో సంప్రదించండి - అపాయింట్‌మెంట్ షెడ్యూల్ చేయండి',
    safeToMonitor: 'పర్యవేక్షించడం సురక్షితం - లక్షణాలను గమనించండి',
    analysisSummary: 'విశ్లేషణ సారాంశం',
    conditionsAnalyzed: 'విశ్లేషించిన పరిస్థితులు',
    possibleConditions: 'సాధ్యమైన పరిస్థితులు',
    match: 'సరిపోలిక',
    symptomsAnalyzed: 'విశ్లేషించిన లక్షణాలు',
    viewCareAdvice: 'సంరక్షణ సలహా చూడండి',
    bookAppointment: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    medicalDisclaimer: 'వైద్య నిరాకరణ: ఈ AI అంచనా సమాచార ప్రయోజనాల కోసం మాత్రమే. వైద్య సమస్యల కోసం ఎల్లప్పుడూ ఆరోగ్య నిపుణులను సంప్రదించండి.',
    
    // Advice
    careAdvice: 'సంరక్షణ సలహా',
    immediateActionRequired: 'తక్షణ చర్య అవసరం',
    scheduleMedicalConsultation: 'వైద్య సంప్రదింపు షెడ్యూల్ చేయండి',
    selfCareMonitoring: 'స్వీయ-సంరక్షణ & పర్యవేక్షణ',
    recommendedNextSteps: 'సిఫార్సు చేసిన తదుపరి దశలు',
    homeCareTips: 'ఇంటి సంరక్షణ చిట్కాలు',
    whenToSeekCare: 'ఎప్పుడు తక్షణ సంరక్షణ తీసుకోవాలి',
    urgentCare: 'అత్యవసర సంరక్షణ',
    callHealthHotline: 'ఆరోగ్య హాట్‌లైన్‌కు కాల్ చేయండి',
    emergency: 'అత్యవసరం',
    callImmediately: 'ప్రాణాంతక లక్షణాలు ఉంటే వెంటనే కాల్ చేయండి',
    
    // Advice texts
    seekEmergency: 'వెంటనే అత్యవసర వైద్య సంరక్షణ తీసుకోండి',
    callEmergencyServices: 'లక్షణాలు మరింత తీవ్రమైతే అత్యవసర సేవలకు కాల్ చేయండి',
    doNotWait: 'వేచి ఉండకండి - సమీపంలోని ఆసుపత్రికి వెళ్ళండి',
    haveSomeoneDrive: 'ఎవరైనా మిమ్మల్ని తీసుకెళ్ళమని చెప్పండి లేదా అంబులెన్స్ పిలవండి',
    contactProvider: '24-48 గంటలలో మీ ఆరోగ్య సేవా ప్రదాతను సంప్రదించండి',
    monitorClosely: 'లక్షణాలను నిశితంగా పర్యవేక్షించండి',
    avoidStrenuous: 'కఠినమైన కార్యకలాపాలను నివారించండి',
    keepDiary: 'లక్షణాల డైరీ ఉంచండి',
    getPlentyRest: 'పుష్కలంగా విశ్రాంతి తీసుకోండి',
    stayHydrated: 'స్పష్టమైన ద్రవాలతో హైడ్రేట్ గా ఉండండి',
    maintainComfortable: 'సౌకర్యవంతమైన గది ఉష్ణోగ్రతను నిర్వహించండి',
    takeOTC: 'అవసరమైతే ఓవర్-ది-కౌంటర్ నొప్పి ఉపశమనం తీసుకోండి',
    monitorForChanges: 'ఏవైనా మార్పుల కోసం లక్షణాలను పర్యవేక్షించండి',
    restAndRecover: 'విశ్రాంతి తీసుకోండి మరియు మీ శరీరాన్ని కోలుకోనివ్వండి',
    contactDoctor: 'లక్షణాలు మరింత తీవ్రమైతే వైద్యుడిని సంప్రదించండి',
    keepTrack: 'మీరు ఎలా అనుభవిస్తున్నారో ట్రాక్ చేయండి',
    getSleep: '7-9 గంటలు నిద్రపోండి',
    drinkWater: 'పుష్కలంగా నీరు తాగండి',
    eatLight: 'తేలికపాటి, పోషకమైన భోజనం తినండి',
    useHumidifier: 'అవసరమైతే హ్యుమిడిఫైయర్ వాడండి',
    takeWarmBaths: 'వెచ్చని స్నానాలు చేయండి',
    symptomsWorsen: 'లక్షణాలు అకస్మాత్తుగా మరింత తీవ్రమవుతాయి',
    difficultyBreathing: 'శ్వాస తీసుకోవడం కష్టం లేదా ఛాతీ నొప్పి',
    highFeverWarning: 'తీవ్ర జ్వరం (103°F/39.4°C పైన)',
    severeHeadache: 'తీవ్ర తలనొప్పి లేదా గందరగోళం',
    persistentVomiting: 'నిరంతర వాంతులు లేదా నిర్జలీకరణ సంకేతాలు',
    
    // History
    noHistoryYet: 'ఇంకా చరిత్ర లేదు',
    checksWillAppear: 'మీ లక్షణ తనిఖీలు ఇక్కడ కనిపిస్తాయి',
    symptoms: 'లక్షణాలు',
    assessment: 'అంచనా',
    
    // Settings
    profileInformation: 'ప్రొఫైల్ సమాచారం',
    fullName: 'పూర్తి పేరు',
    enterName: 'మీ పేరు నమోదు చేయండి',
    age: 'వయస్సు',
    enterAge: 'మీ వయస్సు నమోదు చేయండి',
    gender: 'లింగం',
    selectGender: 'లింగం ఎంచుకోండి',
    male: 'పురుషుడు',
    female: 'స్త్రీ',
    other: 'ఇతర',
    preferNotToSay: 'చెప్పడం ఇష్టం లేదు',
    privacyData: 'గోప్యత & డేటా',
    allDataOnDevice: 'అన్ని డేటా పరికరంలో ఉంటుంది',
    healthInfoPrivate: 'మీ ఆరోగ్య సమాచారం స్థానికంగా ప్రాసెస్ చేయబడుతుంది మరియు బాహ్య సర్వర్‌లకు ఎప్పుడూ పంపబడదు.',
    saveSymptomHistory: 'లక్షణ చరిత్ర సేవ్ చేయండి',
    keepRecord: 'మీ తనిఖీల రికార్డు ఉంచండి',
    analyticsAnonymous: 'అనలిటిక్స్ (అనామక)',
    helpImprove: 'యాప్‌ను మెరుగుపరచడంలో సహాయపడండి',
    appPreferences: 'యాప్ ప్రాధాన్యతలు',
    language: 'భాష / Language',
    darkMode: 'డార్క్ మోడ్',
    useDarkTheme: 'డార్క్ థీమ్ వాడండి',
    notifications: 'నోటిఫికేషన్లు',
    healthReminders: 'ఆరోగ్య రిమైండర్లు',
    getReminded: 'లక్షణాలు తనిఖీ చేయమని గుర్తు చేయండి',
    appointmentReminders: 'అపాయింట్‌మెంట్ రిమైండర్లు',
    remindersForBooked: 'బుక్ చేసిన అపాయింట్‌మెంట్‌ల కోసం రిమైండర్లు',
    dataManagement: 'డేటా నిర్వహణ',
    clearAllHistory: 'మొత్తం చరిత్రను తొలగించండి',
    appVersion: 'AI-శక్తి ఆరోగ్య పరీక్ష v1.0.0',
    copyright: '© 2024 - మీ ఆరోగ్యం కోసం తయారు చేయబడింది',
    
    // Appointment Booking
    backToResults: 'ఫలితాలకు తిరిగి వెళ్ళండి',
    findNearbyClinics: 'సమీపంలోని క్లినిక్‌లను కనుగొనండి',
    selectClinic: 'అపాయింట్‌మెంట్ బుక్ చేయడానికి క్లినిక్ ఎంచుకోండి',
    nextAvailable: 'తదుపరి అందుబాటు',
    select: 'ఎంచుకోండి',
    bookingAt: 'బుకింగ్',
    patientInformation: 'రోగి సమాచారం',
    phoneNumber: 'ఫోన్ నంబర్',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    reasonForVisit: 'సందర్శన కారణం',
    briefDescription: 'మీ లక్షణాల సంక్షిప్త వివరణ',
    chooseDifferentClinic: 'వేరే క్లినిక్ ఎంచుకోండి',
    confirmAppointment: 'అపాయింట్‌మెంట్ నిర్ధారించండి',
    
    // Loading
    analyzingSymptoms: 'మీ లక్షణాలను విశ్లేషిస్తోంది',
    aiProcessing: 'మా AI మీ సమాచారాన్ని ప్రాసెస్ చేస్తోంది...',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.en;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  useEffect(() => {
    const saved = localStorage.getItem('app-language');
    if (saved && saved !== language) {
      setLanguageState(saved as Language);
    }
  }, []);

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
